platform :ios,'8.0'
inhibit_all_warnings!

target "WTBaseCoreDemo" do
    pod 'WTBaseCore', :git => "https://github.com/aliang666/WTBaseCore.git"
    #pod 'WTBaseCore', :git => "https://github.com/aliang666/WTBaseCore.git" , :tag => "0.0.1"
end

